<a href="https://colab.research.google.com/github/sheelaj123/PyTorch-Demos/blob/main/Pytorch_Step_by_Step.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch torchvision

In [ ]:
import torch

##Tensor generation using pytorch:-

#Element wise Operation:-

In [ ]:
x = torch.empty(1)
x

tensor([6.5258e+24])

In [ ]:
x = torch.empty(5,3) # 5x3 matrix
x

tensor([[3.0029e+19, 4.5181e-41, 7.1263e+24],
        [3.3251e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.1111e+08, 7.7052e+31, 7.2148e+22],
        [1.5766e-19, 1.0256e-08, 1.0255e-08]])

#3 D matrix:

In [ ]:
x = torch.empty(2,5,3) # 5x3 matrix
x

tensor([[[ 7.6719e+24,  3.3251e-41,  7.1111e+24],
         [ 3.3251e-41,  8.9683e-44,  0.0000e+00],
         [ 1.1210e-43,  0.0000e+00, -1.8278e-17],
         [ 3.3256e-41,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  1.3593e-43],
         [ 0.0000e+00,  7.4996e+24,  3.3251e-41]]])

In [ ]:
x = torch.empty(2,2,5,3) # 5x3 matrix
x

tensor([[[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 2.4367e+24,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 1.4013e-45,  0.0000e+00,  7.7070e+24],
          [ 3.3251e-41,  0.0000e+00,  0.0000e+00],
          [ 3.2234e+21,  3.3251e-41,  0.0000e+00],
          [ 0.0000e+00, -2.7098e+16,  4.5179e-41],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 1.4013e-45,  0.0000e+00,  4.2039e-45],
          [ 0.0000e+00,

Using rand() ▶

In [ ]:
x = torch.rand(5,3) # Tensor will be generated  with 5 Rows and 3 Columns
x

tensor([[0.4385, 0.4462, 0.0073],
        [0.5406, 0.5705, 0.6479],
        [0.0549, 0.7769, 0.3394],
        [0.9198, 0.0400, 0.4853],
        [0.3421, 0.4824, 0.8691]])

Using zeros() ▶

In [ ]:
x = torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

using ones() ▶

In [ ]:
x = torch.ones(5,3) #similar to np.ones or np.zeros
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor addition operation ▶

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x + y

In [ ]:
print(x)
print(y)
print(z) # Sum of tensors

tensor([[0.0892, 0.2690],
        [0.6009, 0.6654]])
tensor([[0.5821, 0.8431],
        [0.5358, 0.9213]])
tensor([[0.6713, 1.1120],
        [1.1366, 1.5868]])


In [ ]:
p = x - y #

In [ ]:
print(p)

tensor([[-0.4929, -0.5741],
        [ 0.0651, -0.2559]])


same way we can perform multiplication, devision operation ⚛

#Slicing of pytorch tensor ▶

In [ ]:
x = torch.rand(5,4)
x

tensor([[0.2448, 0.4344, 0.1452, 0.1761],
        [0.6789, 0.1691, 0.4323, 0.4998],
        [0.6356, 0.3274, 0.5258, 0.2424],
        [0.8333, 0.0965, 0.6569, 0.7272],
        [0.7501, 0.8339, 0.7892, 0.9697]])

In [ ]:
# to display all rows with  only first 2 columns:

x[:,:2]

tensor([[0.2448, 0.4344],
        [0.6789, 0.1691],
        [0.6356, 0.3274],
        [0.8333, 0.0965],
        [0.7501, 0.8339]])

In [ ]:
x[:3,:]

tensor([[0.2448, 0.4344, 0.1452, 0.1761],
        [0.6789, 0.1691, 0.4323, 0.4998],
        [0.6356, 0.3274, 0.5258, 0.2424]])

In [ ]:
#all rows with last 2 columns
x[:,2:]

tensor([[0.1452, 0.1761],
        [0.4323, 0.4998],
        [0.5258, 0.2424],
        [0.6569, 0.7272],
        [0.7892, 0.9697]])

#Re-Shaping of pytorch tensor ▶

##view ()  method

In [ ]:
x = torch.rand(5,4)
x

tensor([[0.0013, 0.2979, 0.3700, 0.4331],
        [0.6952, 0.3083, 0.9285, 0.5732],
        [0.8580, 0.2416, 0.2511, 0.9753],
        [0.2392, 0.0942, 0.7064, 0.3568],
        [0.2249, 0.1875, 0.4050, 0.9199]])

In [ ]:
#Above example is 5x4 matrix


#let's reshape it to 1 D

y = x.view(20) # 5*4 = 20 , if you put any other no. its will causing error.
y

tensor([0.0013, 0.2979, 0.3700, 0.4331, 0.6952, 0.3083, 0.9285, 0.5732, 0.8580,
        0.2416, 0.2511, 0.9753, 0.2392, 0.0942, 0.7064, 0.3568, 0.2249, 0.1875,
        0.4050, 0.9199])

In [ ]:
#let's reshape it to 2 D

y = x.view(-1,10) #items will be In two matrix forms.
y

tensor([[0.0013, 0.2979, 0.3700, 0.4331, 0.6952, 0.3083, 0.9285, 0.5732, 0.8580,
         0.2416],
        [0.2511, 0.9753, 0.2392, 0.0942, 0.7064, 0.3568, 0.2249, 0.1875, 0.4050,
         0.9199]])

#Convert Torch Tensor to Numpy Or Vice-Versa :)

In [ ]:
import numpy as np
import torch

In [ ]:
x = torch.ones(5,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

conversion of tensor to numpy:

Syntax:

x.numpy()

In [ ]:
y = x.numpy()
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

conversion of numpy to tensor :

Syntax:

y= torch.from_numpy(x)

In [ ]:
x = np.ones((5,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
y= torch.from_numpy(x)
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

#shift tensor to  GPU:

if available:

in colab:  go to run time change runtime --

change to GPU

In [ ]:
# to know weather gpu available:

if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")
device

device(type='cpu')

Requires_grad argument :

In [ ]:
x = torch.ones(5,4, requires_grad=True)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

#Autograd Pytorch:

In [ ]:
import torch

x = torch.rand(4, requires_grad = True)

x

tensor([0.0828, 0.1655, 0.1866, 0.3338], requires_grad=True)

In [ ]:
y = x+5

y

tensor([5.0828, 5.1655, 5.1866, 5.3338], grad_fn=<AddBackward0>)

this will generate grad function like:  grad_fn= < AddBackward0>

In [ ]:
y = torch.rand(3)
y

tensor([0.4145, 0.4870, 0.0227])

In [ ]:
y = torch.rand(3, requires_grad =True)
y

tensor([0.3012, 0.2505, 0.2249], requires_grad=True)

In [ ]:
x = y+5
x

tensor([5.3012, 5.2505, 5.2249], grad_fn=<AddBackward0>)

In [ ]:
z=  x*x*3
z

tensor([84.3069, 82.7042, 81.8990], grad_fn=<MulBackward0>)

In [ ]:
z = z.mean() #scalar value
z.backward() # dz/dx
x.grad

<ipython-input-139-bff4891699a8>:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  x.grad


let's suppose  i don't want to show this grad function : --

In [ ]:
x = torch.rand(4, requires_grad =True)
x

tensor([0.4147, 0.9693, 0.5438, 0.4918], requires_grad=True)

In [ ]:
with torch.no_grad():
  y= x+5
y

tensor([5.4147, 5.9693, 5.5438, 5.4918])

#Simple trainig examples to understands this concept:

In [ ]:
import torch
w= torch.ones(3, requires_grad=True)
w


#dummy training

for epoch in range(3):
  output = (3*w).sum()
  output.backward()
  print(w.grad)
  w.grad.zero_()

tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])


#BackPropagation  In Pytorch:

Let's understands with example: -

In [ ]:
import torch

In [ ]:
x = torch.tensor(3.0)
Y = torch.tensor(36.0)

In [ ]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

In [ ]:
#forward pass and compute loss:
z = a*x*x
y= b*z

In [ ]:
J = 0.5*(y-Y)*(y-Y)

In [ ]:
J.backward()
a.grad


tensor(486.)

In [ ]:
b.grad

tensor(324.)

In [ ]:
a.grad.zero_()
b.grad.zero_()

tensor(0.)

#Data Loader in PyTorch:

In [ ]:
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader

In [ ]:
x = np.random.randn(150,5)
y = np.random.randn(150,3)

In [ ]:
class OurDataset(Dataset):

  def __init__(self,x,y):
    #data loading
    self.x = torch.from_numpy(x)
    self.x = torch.from_numpy(y)
  def __getitem__(self, index):
    #dataset[0]
    return self.x[index],self.y[index]
  def __len__(self):
    #length
    return len(self.x)

In [ ]:
x= np.random.randn(150,5)
y= np.random.randn(150,3)

In [ ]:
x[:20,:]

array([[-1.06954618, -0.1232431 ,  2.73509599,  0.27166586, -1.01280161],
       [ 0.97747222, -1.57285776, -0.23157759, -0.45507904,  0.08647403],
       [ 0.43276546, -0.7490895 ,  0.03864961, -1.12025354, -0.54842298],
       [ 0.6396207 ,  1.5674532 ,  0.12780379, -0.74623057, -0.74937877],
       [ 0.20252831, -1.21156962, -0.43298061,  1.02198938, -0.96684093],
       [ 0.79493274, -1.44909803, -1.20096714, -0.27036057,  0.11573142],
       [-0.84732566,  0.96826613,  0.17209909, -0.3316624 , -1.39379694],
       [ 0.51777703,  0.15296821,  0.54270476, -1.7928608 ,  1.58786102],
       [-1.38050966, -0.71452328,  0.89179101, -1.18500609, -0.20452775],
       [ 1.39123854,  1.6777376 , -2.59349565,  1.15527179, -1.63051397],
       [ 1.0087756 , -0.99798682, -1.46156191,  0.01426458, -0.06921873],
       [ 0.96889318, -0.5036713 ,  0.42072586,  0.98047034, -0.85060904],
       [-1.50411769, -0.03906123, -0.60583063,  0.2277675 ,  1.08650152],
       [-0.85111951,  0.68593744,  0.1

In [ ]:
dataset = OurDataset(x,y)
dataloader = DataLoader(dataset =dataset, batch_size = 5, shuffle=True)

dataiterator = iter(dataloader)

for i, (inputs, labels) in enumerate(dataloader):
  print(inputs)
  print(labels)
  break

In [ ]:
next(dataiterator)

#DATA AUGMENTATION AND TRANSFORMATION in PyTorch ▶

In [ ]:
import numpy as np
from torch.utils.data import Dataset, DataLoader
import torch
import torchvision

In [ ]:
class OurDataset(Dataset):

  def __init__(self,X,y,transforms = None):
    self.X =torch.from_numpy(X)
    self.y =torch.from_numpy(y)
    self.transforms = transforms

  def __getitem__(self,index):
    #dataset[0]
    if self.transforms:
      self.X,self.y = self.transforms(self.X,self.y)
    return self.X[index], self.y[index]

  def __len__(self):
    return len(self.X)

  class ToTensors:
    def __call__(self,X,y):
      return torch.from_numpy(X),torch.from_numpy(y)



In [ ]:
X = np.random.randn(150,5)
y = np.random.randn(150,1)

In [ ]:
dataset = OurDataset(X,y, transforms = ToTensors())
first_data =dataset[0]
inputs, label =first_data
inputs